import { ReviewReport, ReviewResult } from "../types/index.js";

export class ReviewReporter {
  formatMarkdownReport(report: ReviewReport): string {
    const { pullRequest, results, summary } = report;

    let markdown = `# 🤖 AI Code Review Report\n\n`;
    markdown += `**Pull Request:** #${pullRequest.pullRequestId} - ${pullRequest.title}\n`;
    markdown += `**Repository:** ${pullRequest.repository}\n`;
    markdown += `**Branch:** ${pullRequest.sourceRefName} → ${pullRequest.targetRefName}\n`;
    markdown += `**Created By:** ${pullRequest.createdBy}\n`;
    markdown += `**Reviewed At:** ${new Date(report.timestamp).toLocaleString()}\n\n`;

    markdown += `## 📊 Summary\n\n`;
    markdown += `| Total Checks | ✅ Passed | ❌ Failed | 🔴 Errors | ⚠️ Warnings | ℹ️ Info |\n`;
    markdown += `|--------------|----------|----------|----------|------------|----------|\n`;
    markdown += `| ${summary.total} | ${summary.passed} | ${summary.failed} | ${summary.errors} | ${summary.warnings} | ${summary.info} |\n\n`;

    // Group results by check name
    const resultsByCheck = new Map<string, ReviewResult[]>();
    for (const result of results) {
      const existing = resultsByCheck.get(result.checkName) || [];
      existing.push(result);
      resultsByCheck.set(result.checkName, existing);
    }

    markdown += `## 📝 Detailed Results\n\n`;

    for (const [checkName, checkResults] of resultsByCheck) {
      const allPassed = checkResults.every((r) => r.passed);
      const icon = allPassed ? "✅" : "❌";
      
      markdown += `### ${icon} ${checkName}\n\n`;

      for (const result of checkResults) {
        const severityIcon = 
          result.severity === "error" ? "🔴" :
          result.severity === "warning" ? "⚠️" : "ℹ️";

        markdown += `${severityIcon} **${result.passed ? "PASS" : "ISSUE"}**: ${result.message}\n`;
        
        if (result.file) {
          markdown += `   📁 File: \`${result.file}\``;
          if (result.line) {
            markdown += ` (line ${result.line})`;
          }
          markdown += `\n`;
        }
        
        if (result.details) {
          markdown += `   💡 Details: ${result.details}\n`;
        }
        
        markdown += `\n`;
      }
    }

    markdown += `\n---\n`;
    markdown += `*Generated by Azure DevOps PR Reviewer powered by GitHub Copilot*\n`;

    return markdown;
  }

  formatConsoleReport(report: ReviewReport): string {
    const { results, summary } = report;

    let output = `\n${"=".repeat(80)}\n`;
    output += `  AI CODE REVIEW REPORT\n`;
    output += `${"=".repeat(80)}\n\n`;

    output += `Summary: ${summary.passed}/${summary.total} checks passed\n`;
    output += `  - Errors:   ${summary.errors}\n`;
    output += `  - Warnings: ${summary.warnings}\n`;
    output += `  - Info:     ${summary.info}\n\n`;

    // Group by check
    const resultsByCheck = new Map<string, ReviewResult[]>();
    for (const result of results) {
      const existing = resultsByCheck.get(result.checkName) || [];
      existing.push(result);
      resultsByCheck.set(result.checkName, existing);
    }

    for (const [checkName, checkResults] of resultsByCheck) {
      const allPassed = checkResults.every((r) => r.passed);
      output += `${allPassed ? "✓" : "✗"} ${checkName}\n`;

      for (const result of checkResults) {
        const prefix = result.severity === "error" ? "  [ERROR]" :
                      result.severity === "warning" ? "  [WARN ]" : "  [INFO ]";
        
        output += `${prefix} ${result.message}\n`;
        
        if (result.file) {
          output += `         File: ${result.file}`;
          if (result.line) {
            output += `:${result.line}`;
          }
          output += `\n`;
        }
      }
      output += `\n`;
    }

    output += `${"=".repeat(80)}\n`;

    return output;
  }

  generateSummary(results: ReviewResult[]): ReviewReport["summary"] {
    const summary = {
      total: results.length,
      passed: 0,
      failed: 0,
      errors: 0,
      warnings: 0,
      info: 0,
    };

    for (const result of results) {
      if (result.passed) {
        summary.passed++;
      } else {
        summary.failed++;
        if (result.severity === "error") summary.errors++;
        else if (result.severity === "warning") summary.warnings++;
        else summary.info++;
      }
    }

    return summary;
  }
}
