import { ReviewReport, ReviewResult } from "../types/index.js";

export class ReviewReporter {
  formatMarkdownReport(report: ReviewReport): string {
    const { pullRequest, results, summary } = report;

    let markdown = `# 🤖 AI Code Review Report\n\n`;
    markdown += `| | |\n|---|---|\n`;
    markdown += `| **Pull Request** | #${pullRequest.pullRequestId} - ${pullRequest.title} |\n`;
    markdown += `| **Repository** | ${pullRequest.repository} |\n`;
    markdown += `| **Branch** | \`${pullRequest.sourceRefName}\` → \`${pullRequest.targetRefName}\` |\n`;
    markdown += `| **Author** | ${pullRequest.createdBy} |\n`;
    markdown += `| **Reviewed** | ${new Date(report.timestamp).toLocaleString()} |\n\n`;

    // Calculate check-level summary (not individual results)
    const resultsByCheck = new Map<string, ReviewResult[]>();
    for (const result of results) {
      const existing = resultsByCheck.get(result.checkName) || [];
      existing.push(result);
      resultsByCheck.set(result.checkName, existing);
    }

    const totalChecks = resultsByCheck.size;
    let passedChecks = 0;
    let failedChecks = 0;
    
    for (const [, checkResults] of resultsByCheck) {
      if (checkResults.every((r) => r.passed)) {
        passedChecks++;
      } else {
        failedChecks++;
      }
    }

    markdown += `## 📊 Summary\n\n`;
    
    if (failedChecks === 0) {
      markdown += `✅ **All ${totalChecks} checks passed!**\n\n`;
    } else {
      markdown += `| ✅ Passed | ❌ Issues Found |\n`;
      markdown += `|:---------:|:---------------:|\n`;
      markdown += `| ${passedChecks}/${totalChecks} | ${failedChecks} |\n\n`;
    }

    markdown += `## 📝 Detailed Results\n\n`;

    // Show failed checks first, then passed checks
    const sortedChecks = [...resultsByCheck.entries()].sort(([, a], [, b]) => {
      const aFailed = a.some((r) => !r.passed);
      const bFailed = b.some((r) => !r.passed);
      if (aFailed && !bFailed) return -1;
      if (!aFailed && bFailed) return 1;
      return 0;
    });

    for (const [checkName, checkResults] of sortedChecks) {
      const allPassed = checkResults.every((r) => r.passed);
      const icon = allPassed ? "✅" : "❌";
      
      markdown += `### ${icon} ${checkName}\n\n`;

      if (allPassed) {
        // For passed checks, just show a simple confirmation
        markdown += `No issues found.\n\n`;
      } else {
        // For failed checks, show details
        const issues = checkResults.filter((r) => !r.passed);
        
        for (const result of issues) {
          const severityIcon = 
            result.severity === "error" ? "🔴" :
            result.severity === "warning" ? "⚠️" : "ℹ️";

          markdown += `${severityIcon} ${result.message}\n`;
          
          if (result.file) {
            markdown += `  - 📁 \`${result.file}\``;
            if (result.line) {
              markdown += ` (line ${result.line})`;
            }
            markdown += `\n`;
          }
          
          if (result.details) {
            markdown += `  - 💡 ${result.details}\n`;
          }
          
          markdown += `\n`;
        }
      }
    }

    markdown += `---\n`;
    markdown += `*Generated by [PR Reviewer](https://github.com) powered by GitHub Copilot*\n`;

    return markdown;
  }

  formatConsoleReport(report: ReviewReport): string {
    const { results, summary } = report;

    // Calculate check-level summary
    const resultsByCheck = new Map<string, ReviewResult[]>();
    for (const result of results) {
      const existing = resultsByCheck.get(result.checkName) || [];
      existing.push(result);
      resultsByCheck.set(result.checkName, existing);
    }

    const totalChecks = resultsByCheck.size;
    let passedChecks = 0;
    
    for (const [, checkResults] of resultsByCheck) {
      if (checkResults.every((r) => r.passed)) {
        passedChecks++;
      }
    }

    let output = `\n${"=".repeat(80)}\n`;
    output += `  AI CODE REVIEW REPORT\n`;
    output += `${"=".repeat(80)}\n\n`;

    output += `Summary: ${passedChecks}/${totalChecks} checks passed\n\n`;

    // Sort: failed first
    const sortedChecks = [...resultsByCheck.entries()].sort(([, a], [, b]) => {
      const aFailed = a.some((r) => !r.passed);
      const bFailed = b.some((r) => !r.passed);
      if (aFailed && !bFailed) return -1;
      if (!aFailed && bFailed) return 1;
      return 0;
    });

    for (const [checkName, checkResults] of sortedChecks) {
      const allPassed = checkResults.every((r) => r.passed);
      output += `${allPassed ? "✓" : "✗"} ${checkName}\n`;

      if (!allPassed) {
        const issues = checkResults.filter((r) => !r.passed);
        for (const result of issues) {
          const prefix = result.severity === "error" ? "  [ERROR]" :
                        result.severity === "warning" ? "  [WARN ]" : "  [INFO ]";
          
          output += `${prefix} ${result.message}\n`;
          
          if (result.file) {
            output += `         File: ${result.file}`;
            if (result.line) {
              output += `:${result.line}`;
            }
            output += `\n`;
          }
        }
      }
      output += `\n`;
    }

    output += `${"=".repeat(80)}\n`;

    return output;
  }

  generateSummary(results: ReviewResult[]): ReviewReport["summary"] {
    const summary = {
      total: results.length,
      passed: 0,
      failed: 0,
      errors: 0,
      warnings: 0,
      info: 0,
    };

    for (const result of results) {
      if (result.passed) {
        summary.passed++;
      } else {
        summary.failed++;
        if (result.severity === "error") summary.errors++;
        else if (result.severity === "warning") summary.warnings++;
        else summary.info++;
      }
    }

    return summary;
  }
}
